name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: yarn
      - run: yarn build
      - uses: softprops/action-gh-release@v2
        with:
          files: dist-zip/dist.zip
          generate_release_notes: true
      - uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: dist-zip/dist.zip
          extension-id: ${{ vars.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
